version: '2'

services:

  database:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "yannbeauxis/metwork:backend_V2"
    # env_file:
    #   - ../build/env/common.env
    volumes:
      - /home/yann/Data/MetWork/database:/srv/metwork/database
      # - ../build/env:/srv/metwork/conf
      # - ../build/scripts:/opt/metwork-scripts
      # - ../../metwork-backend:/opt/metwork-backend
    stdin_open: true
    tty: true
    user: metwork
    ports: 
      - 5432:5432
    command: /opt/conda/envs/metwork/bin/postgres -D /srv/metwork/database -c log_connections=yes -c log_destination='stderr' -h 0.0.0.0 # -d 5
