version: '2'

services:

  database:
    build:
      context: ./docker-postgres-rdkit/
      dockerfile: Dockerfile
    image: "yannbeauxis/metwork:db"
    container_name: "metwork_db"
    environment: 
      - POSTGRES_USER=metwork
      - POSTGRES_PASSWORD=METWORK_DB_PASSWORD
      - PGDATA=/srv/metwork/database
    volumes:
      - ./initdb-metwork.sh:/docker-entrypoint-initdb.d/initdb-metwork.sh
      - /home/yann/Data/MetWork/dev_dataset/database:/srv/metwork/database
    # user: metwork
    ports: 
      - 5432:5432
    # command: postgres -D /srv/metwork/database -c log_connections=yes -c log_destination='stderr' -h 0.0.0.0 # -d 5

  broker:
    image: "rabbitmq:3-management"
    container_name: "metwork_broker"
    environment: 
      - RABBITMQ_DEFAULT_USER=metwork
      - RABBITMQ_DEFAULT_PASS=METWORK_BROKER_PASSWORD
      - RABBITMQ_DEFAULT_VHOST=metwork

  cache:
    image: "memcached:1.6-alpine"
    container_name: "metwork_cache"

  docker_hoster:
    # To be able to access to docker containers names in dns resolution.
    image: dvdarias/docker-hoster
    container_name: "metwork_docker_hoster"
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /etc/hosts:/tmp/hosts